### ISSUE TITLE
Global Search is broken because of missing field

### ISSUE THREAD

**Issue by samdharris** [stepanenko3/nova-settings#8]
When using global search in Nova, the below exception is thrown. It appears to be related to https://github.com/stepanenko3/nova-settings/blob/master/src/Resources/Settings.php

Version Information
===
Laravel Nova version: 4.24.4
Laravel version: 9.52.10
nova-settings version: 1.0.5

Stack Trace
===
```
[previous exception] [object] (PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'settings.name' in 'where clause' at /home/vagrant/code/Parents/vendor/laravel/framework/src/Illuminate/Database/Connection.php:444)
[stacktrace]
#0 /home/vagrant/code/Parents/vendor/laravel/framework/src/Illuminate/Database/Connection.php(444): PDO->prepare()
#1 /home/vagrant/code/Parents/vendor/laravel/framework/src/Illuminate/Database/Connection.php(753): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}()
#2 /home/vagrant/code/Parents/vendor/laravel/framework/src/Illuminate/Database/Connection.php(720): Illuminate\\Database\\Connection->runQueryCallback()
#3 /home/vagrant/code/Parents/vendor/laravel/framework/src/Illuminate/Database/Connection.php(456): Illuminate\\Database\\Connection->run()
#4 /home/vagrant/code/Parents/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2885): Illuminate\\Database\\Connection->cursor()
#5 /home/vagrant/code/Parents/vendor/laravel/framework/src/Illuminate/Collections/LazyCollection.php(788): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()
#6 /home/vagrant/code/Parents/vendor/laravel/framework/src/Illuminate/Collections/LazyCollection.php(788): Illuminate\\Support\\LazyCollection->Illuminate\\Support\\{closure}()
#7 /home/vagrant/code/Parents/vendor/laravel/framework/src/Illuminate/Collections/LazyCollection.php(788): Illuminate\\Support\\LazyCollection->Illuminate\\Support\\{closure}()
#8 /home/vagrant/code/Parents/vendor/laravel/nova/src/GlobalSearch.php(66): Illuminate\\Support\\LazyCollection->Illuminate\\Support\\{closure}()
#9 [internal function]: Laravel\\Nova\\GlobalSearch->getSearchResults()
```

**Comment by chrillep** [comment]
https://github.com/stepanenko3/nova-settings/blob/7fce9ff74ba1ab243ce014db8119dbc4d9799e0d/src/Resources/Settings.php#L24-L30
